import localFont from "next/font/local";
import "./globals.css";
import {Outfit} from "next/font/google"

export const metadata = {
  title: "AI Note Taking - SASS Application",
  description: "Generated by create next app",
};

const outfit = Outfit({subsets: ['latin']})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        {children}
      </body>
    </html>
  );
}
